// <auto-generated />
namespace MyElearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_mig_instructor_title_coverimage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_mig_instructor_title_coverimage));
        
        string IMigrationMetadata.Id
        {
            get { return "202310140551423_add_mig_instructor_title_coverimage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
