// <auto-generated />
namespace MyElearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Upd_mig_Galery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Upd_mig_Galery));
        
        string IMigrationMetadata.Id
        {
            get { return "202310131159225_Upd_mig_Galery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
