// <auto-generated />
namespace MyElearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class upd_mig_contact_linkedin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upd_mig_contact_linkedin));
        
        string IMigrationMetadata.Id
        {
            get { return "202310130949273_upd_mig_contact_linkedin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
